### ISSUE TITLE
[bug]: npx shadcn init hangs while creating nextjs project

### ISSUE THREAD

**Issue by matt-seifert** [shadcn-ui/ui#5508] opened 2024-10-22 13:35 UTC
### Describe the bug

When I run the command "npx shadcn init" or "npx shadcn@latest init", I'm prompted with the first two questions (Would you like to start a new nextjs project/What is your project's name). Once I select the name, the CLI says "Creating a new Next.js project. This may take a few minutes.". But it just sits there indefinitely and never creates anything, forcing me to eventually terminate the process. This was working fine 2 days ago, but I've been getting this bug since yesterday afternoon. Have verified this bug is operating similarly on 2 of my machines, and I had my friend verify on his machine as well.
![image](https://github.com/user-attachments/assets/a8d91524-827e-4a21-974d-10f212f450d5)

### Affected component/components

All

### How to reproduce

Run "npx shadcn init" command and try to start a new nextjs project.

### System Info

```bash
Windows 11 Version	10.0.26100 Build 26100
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by Wangbaoqi** [comment] 2024-10-22 13:52
me too

**Comment by shokks** [comment] 2024-10-22 13:57
Me too. 

Is this caused by the NextJS15 released last night?

clean install of `create-next-app@latest` gives you a fresh copy where if you run `npx shadcn@latest init` it throws issues with the fact that nextjs15 ususes, react@19.0.0-rc-65a56d0e-20241020 and @radix-ui/react-icons & @radix-ui/react-icons@1.3.0 uses react@"^16.x || ^17.x || ^18.x"

Dependency errors, may be?

**Comment by matt-seifert** [comment] 2024-10-22 14:18
> Me too.
> 
> Is this caused by the NextJS15 released last night, where it supports React@19 RC?
> 
> clean install of `create-next-app@latest` gives you a fresh copy where, if you run, `npx shadcn@latest init` throws error with the fact that nextjs15 uses, react@19.0.0-rc-65a56d0e-20241020 and @radix-ui/react-icons & @radix-ui/react-icons@1.3.0 use react@"^16.x || ^17.x || ^18.x"
> 
> Dependency errors, maybe?

Great sleuthing there! Sounds like a strong possibility.

**Comment by k3yboardnerd** [comment] 2024-10-22 15:25
**me too**

 npx shadcn@latest init     
✔ Preflight checks.
✔ Verifying framework. Found Next.js.
✔ Validating Tailwind CSS.
✔ Validating import alias.
√ Which style would you like to use? » New York
√ Which color would you like to use as the base color? » Zinc
√ Would you like to use CSS variables for theming? ... no / yes
✔ Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.ts
✔ Updating app\globals.css
⠧ Installing dependencies.
Something went wrong. Please check the error below for more details.
If the problem persists, please open an issue on GitHub.

Command failed with exit code 1: npm install tailwindcss-animate class-variance-authority lucide-react @radix-ui/react-icons clsx tailwind-merge
npm error code ERESOLVE
npm error ERESOLVE unable to resolve dependency tree
npm error
npm error While resolving: wifckerism-studio@0.1.0
npm error Found: react@19.0.0-rc-65a56d0e-20241020
npm error node_modules/react
npm error   react@"19.0.0-rc-65a56d0e-20241020" from the root project
npm error
npm error Could not resolve dependency:
npm error peer react@"^16.x || ^17.x || ^18.x" from @radix-ui/react-icons@1.3.0
npm error node_modules/@radix-ui/react-icons
npm error   @radix-ui/react-icons@"*" from the root project
npm error
npm error Fix the upstream dependency conflict, or retry
npm error this command with --force or --legacy-peer-deps
npm error to accept an incorrect (and potentially broken) dependency resolution.
npm error
npm error

**Comment by JeffinJ** [comment] 2024-10-22 15:45
Same here, a new app with NextJS 15, and when installing Shadcn UI
![nextjs15shadcnui-error](https://github.com/user-attachments/assets/e342c286-70ba-401c-9aeb-8097d9d77682)

**Comment by codmanuel26** [comment] 2024-10-22 16:00
I'm having the same problem it was working yesterday in the morning

**Comment by matt-seifert** [comment] 2024-10-22 17:23
> Same problem for me. Peer dependency issue for sure because of the different react version.
> 
> If you need it asap, you can use the --legacy-peer-deps flag: `npx --legacy-peer-deps shadcn@latest init`
> 
> This works for now and we should then later be able to update it to the latest version 😄

Thanks for the response and suggestion. Unfortunately this command still causes it to hang while creating the Next.js project. I was, however, able to do "npx create-next-app@14.2", followed by "npx shadcn init", and it seems to scaffold everything correctly. I believe Next.js version before the breaking change is 14.2, so this puts the project one version behind current. I think once things are fixed, the update to Next.js 15 should be simple.  Still would rather just have the simple "npx shadcn init" worrking correctly!

**Comment by codmanuel26** [comment] 2024-10-22 21:30
how would I do this to work with V0's block system

**Comment by aajuu19** [comment] 2024-10-23 08:17
> > Same problem for me. Peer dependency issue for sure because of the different react version.
> > If you need it asap, you can use the --legacy-peer-deps flag: `npx --legacy-peer-deps shadcn@latest init`
> > This works for now and we should then later be able to update it to the latest version 😄
> 
> Thanks for the response and suggestion. Unfortunately this command still causes it to hang while creating the Next.js project. I was, however, able to do "npx create-next-app@14.2", followed by "npx shadcn init", and it seems to scaffold everything correctly. I believe Next.js version before the breaking change is 14.2, so this puts the project one version behind current. I think once things are fixed, the update to Next.js 15 should be simple. Still would rather just have the simple "npx shadcn init" worrking correctly!

Sorry, i actually forgot to mention that in my comment. If you are eager to use next 15 immediately, you have to install next 15 manually first `npx create-next-app@latest` and after that you can install shadcn using the legacy-peer-deps flag `npx --legacy-peer-deps shadcn@latest init`.

**Comment by shadcn** [comment] 2024-10-28 16:12
I'm working on a fix. Let's use https://github.com/shadcn-ui/ui/issues/5557 to track since they are related.

**Closed by shadcn** 2024-10-28 16:12 UTC
Labels: bug
