### ISSUE TITLE
Select having backdrop behaviour

### ISSUE THREAD

**Issue by Sandeep13-web** [shadcn-ui/ui#1809] opened 2023-10-23 11:45 UTC
Whenever i open the select, the body is not scrollable. Is there something i need to pass as props in order to solve this problem?

**Comment by alexsilvar** [comment] 2023-10-23 11:50
I have the same problem when I put my select inside a Dialog, if I set `modal={false}` on the Dialog it works as expected. I'm still seeking for the proper fix.

**Comment by matheralvs** [comment] 2023-10-24 03:19
@Sandeep13-web & @alexsilvar I wrapped my Select content in a ScrollArea component and it worked.

**Comment by shadcn** [comment] 2023-10-24 12:03
@Sandeep13-web This is a known issue (or maybe intended behavior?). There's a PR here https://github.com/radix-ui/primitives/pull/2253 waiting for feedback from the Radix team.

I'll close this one for now and continue tracking there. Feel free to reopen if you have any other question. Thank you.

**Closed by shadcn** 2023-10-24 12:03 UTC

**Comment by leognmotta** [comment] 2024-12-14 03:07
that is still a problem
