### ISSUE TITLE
[bug]: Save changes button in Edit Profile dialog does not close the dialog

### ISSUE THREAD

**Issue by ausane** [shadcn-ui/ui#4429] opened 2024-07-27 10:54 UTC
### Describe the bug

On the [Dialog component page](https://ui.shadcn.com/docs/components/dialog), there is an "Edit Profile" button that opens a dialog. Inside this dialog, there is a "Save changes" button that should close the dialog when clicked, but it does not.

### Expected behavior
The dialog should close when the "Save changes" button is clicked.

### Screenshot
![Screenshot 2024-07-27 151931](https://github.com/user-attachments/assets/d6e8107f-4d74-43ec-b3ad-30a278a5a8bc)

### Affected component/components

Dialog

### How to reproduce

1. Go to [Dialog component page](https://ui.shadcn.com/docs/components/dialog).
2. Click on the "Edit Profile" button to open the dialog.
3. Click on the "Save changes" button.
4. Observe that the dialog does not close.

### Codesandbox/StackBlitz link

https://stackblitz.com/edit/stackblitz-starters-vq4tta

### System Info

```bash
- OS: Windows
- Browser: Chrome
- Version: 0.8.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by walid1508** [comment] 2024-07-27 15:39
Hi @ausane,

After reviewing the behavior you described, I wanted to clarify that the Save changes button does not automatically close the dialog by design. This is intentional to handle cases where, for example, a login form might be inside the dialog, and closing it automatically even when the input is invalid would not be ideal.

To implement the behavior where the dialog closes when the Save changes button is clicked, you can manage the dialog state using useState. Here is a corrected version of the code:

<img width="1312" alt="Capture d’écran, le 2024-07-27 à 11 35 24" src="https://github.com/user-attachments/assets/0400d943-e07b-4483-a910-80c59f7dbbf7">

This code will ensure the dialog closes when the Save changes button is clicked.

**Comment by ausane** [comment] 2024-07-27 17:17
nice! thank you @walid1508

**Closed** 2024-07-28 03:44 UTC
Labels: bug
