### ISSUE TITLE
Carousel imported types are no longer available on module "embla-carousel-react"

### ISSUE THREAD

**Issue by aech98** [shadcn-ui/ui#2376] opened 2024-01-11 07:26 UTC
Types **EmblaCarouselType**, **EmblaOptionsType** and **EmblaPluginType** are no longer available on module `embla-carousel-react`. The types have been migrated to `embla-carousel`

### Expected behaviour
![Screenshot (6)](https://github.com/shadcn-ui/ui/assets/43680537/208f2860-5e66-4107-aa94-c03aa033b842)

### Current behaviour
![Screenshot (5)](https://github.com/shadcn-ui/ui/assets/43680537/ac8b89b1-b989-4820-9d15-c03ec77edb5f)

**Comment by statusunknown418** [comment] 2024-01-11 22:38
upvoting

**Comment by shadcn** [comment] 2024-01-14 08:29
@aech98 Closing this as duplicate of https://github.com/shadcn-ui/ui/issues/2281. Let's track there. Thank you.

**Closed by shadcn** 2024-01-14 08:29 UTC
