### ISSUE TITLE
[bug]: Laravel New CLI ignores aliases / Components are installed in the wrong directory

### ISSUE THREAD

**Issue by ivan-plotnikov** [shadcn-ui/ui#5433] opened 2024-10-18 23:41 UTC
### Describe the bug

The old version of the CLI installed my components correctly, in the resources/js/components folder
In the new version, no matter what I change, components are ALWAYS installed in components/ui in the root of the project. Changing the aliases does not affect anything.
I created a new Laravel application following the instructions in the documentation, and it has the same behavior.

What is particularly mind-blowing is that if you create a src folder in the root of the project, it will always install components there, even though I have not specified this folder as a path/alias anywhere.

Installing with the --path option also fails.

Expected behavior: components are installed in resources/js/components/ui folder
Current behavior: components are installed in the components/ui folder

**components.json**
```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "resources/css/app.css",
    "baseColor": "zinc",
    "cssVariables": true,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}
```

**tsconfig.json**
```json
{
    "compilerOptions": {
        "allowJs": true,
        "module": "ESNext",
        "moduleResolution": "bundler",
        "jsx": "react-jsx",
        "strict": true,
        "isolatedModules": true,
        "target": "ESNext",
        "esModuleInterop": true,
        "forceConsistentCasingInFileNames": true,
        "skipLibCheck": true,
        "noEmit": true,
        "paths": {
            "@/*": ["./resources/js/*"],
            "ziggy-js": ["./vendor/tightenco/ziggy"]
        }
    },
    "include": ["resources/js/**/*.ts", "resources/js/**/*.tsx", "resources/js/**/*.d.ts"]
}
```

**vite.config.js**
```js
import { defineConfig } from 'vite';
import laravel from 'laravel-vite-plugin';
import react from '@vitejs/plugin-react';

export default defineConfig({
    plugins: [
        laravel({
            input: 'resources/js/app.tsx',
            refresh: true,
        }),
        react(),
    ],
});
```

Installation log:
plotnikov@MacBook-Air-Ivan my-app % npx shadcn init
Need to install the following packages:
shadcn@2.1.0
Ok to proceed? (y) y

✔ Preflight checks.
✔ Verifying framework. Found Laravel.
✔ Validating Tailwind CSS.
✔ Validating import alias.
✔ Which style would you like to use? › Default
✔ Which color would you like to use as the base color? › Zinc
✔ Would you like to use CSS variables for theming? … no / yes
✔ Writing components.json.
✔ Checking registry.
✔ Updating tailwind.config.js
✔ Updating resources/css/app.css
✔ Installing dependencies.
✔ Created 1 file:
  - lib/utils.ts

Success! Project initialization completed.
You may now add components.

### Affected component/components

All components

### How to reproduce

1) Install new Laravel App by [docs](https://ui.shadcn.com/docs/installation/laravel)
2) Add any component, e.g. `npx shadcn@latest add button`

### System Info

```bash
macOS 15.0, node v22.9.0
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [x] I've searched for existing issues

**Comment by gera919** [comment] 2024-10-19 02:53
Same issue here

**Comment by treppilk** [comment] 2024-10-19 06:31
+1

**Comment by rahmat-dev** [comment] 2024-10-19 07:42
+1

even when I running init command, the utils.ts file is created on ./lib/utils.ts not ./resources/js/lib/utils.ts

**Comment by vffuunnyy** [comment] 2024-10-19 15:20
+1

**Comment by Boendestodet** [comment] 2024-10-19 16:54
+1

**Comment by muhammadaldan** [comment] 2024-10-19 17:14
+1

**Comment by hallwack** [comment] 2024-10-19 18:01
+1

**Comment by dscamargo** [comment] 2024-10-19 18:01
+1

**Comment by anthonyholmes** [comment] 2024-10-19 20:12
+1

**Comment by mmmoli** [comment] 2024-10-19 21:31
+1

**Comment by MrBisbis631** [comment] 2024-10-19 21:34
+1

**Comment by tobiaswendling** [comment] 2024-10-20 11:59
+1

**Comment by Cedrickkk** [comment] 2024-10-20 13:28
+1

**Comment by lucasfeliciano** [comment] 2024-10-20 15:37
If I clone the repo and run the tests, some tests fails. Coincidently it is related to file paths.

![image](https://github.com/user-attachments/assets/30769e60-d871-4c6a-b932-7cb5cdb13f4d)

On top of that the `getRegistryItemFileTargetPath` function from `packages/shadcn/src/utils/registry/index.ts` is not being tested at all. 

This function is used on `packages/shadcn/src/utils/updaters/update-files.ts`, which is used on `packages/shadcn/src/utils/add-components.ts`, and finally on `packages/shadcn/src/commands/add.ts`

Which is exactly the command that we are experiencing issues.

First time looking at this code base and I didn't investigated in depth, but it seems relevant enough to share.

**Comment by youssefhussein** [comment] 2024-10-20 16:17
+1

BRING THE OLD CLI BACKK

**Comment by lucasfeliciano** [comment] 2024-10-20 17:09
I think I found the issue and it's not related with my comment above.

## Bug 

The `filePath` and `targetDir` is being overwritten here on line `74`: 

https://github.com/shadcn-ui/ui/blob/3259fb7ca165b0ae11124257a20b71001049ecca/packages/shadcn/src/utils/updaters/update-files.ts#L69-L76


On line `69`  and `71` the `targetDir` and `filePath` respectively, are what we expect based on what we define on `components.json`! 

The `file.target` on line `74` comes from the registry. For example, for the Alert component see the following url:
https://ui.shadcn.com/r/styles/default/alert.json

Response from URL above:
```json
{
  "name": "alert",
  "type": "registry:ui",
  "files": [
    {
      "path": "ui/alert.tsx",
      "content": "import * as React from \"react\"\nimport { cva, type VariantProps } from \"class-variance-authority\"\n\nimport { cn } from \"@/lib/utils\"\n\nconst alertVariants = cva(\n  \"relative w-full rounded-lg border p-4 [&>svg~*]:pl-7 [&>svg+div]:translate-y-[-3px] [&>svg]:absolute [&>svg]:left-4 [&>svg]:top-4 [&>svg]:text-foreground\",\n  {\n    variants: {\n      variant: {\n        default: \"bg-background text-foreground\",\n        destructive:\n          \"border-destructive/50 text-destructive dark:border-destructive [&>svg]:text-destructive\",\n      },\n    },\n    defaultVariants: {\n      variant: \"default\",\n    },\n  }\n)\n\nconst Alert = React.forwardRef<\n  HTMLDivElement,\n  React.HTMLAttributes<HTMLDivElement> & VariantProps<typeof alertVariants>\n>(({ className, variant, ...props }, ref) => (\n  <div\n    ref={ref}\n    role=\"alert\"\n    className={cn(alertVariants({ variant }), className)}\n    {...props}\n  />\n))\nAlert.displayName = \"Alert\"\n\nconst AlertTitle = React.forwardRef<\n  HTMLParagraphElement,\n  React.HTMLAttributes<HTMLHeadingElement>\n>(({ className, ...props }, ref) => (\n  <h5\n    ref={ref}\n    className={cn(\"mb-1 font-medium leading-none tracking-tight\", className)}\n    {...props}\n  />\n))\nAlertTitle.displayName = \"AlertTitle\"\n\nconst AlertDescription = React.forwardRef<\n  HTMLParagraphElement,\n  React.HTMLAttributes<HTMLParagraphElement>\n>(({ className, ...props }, ref) => (\n  <div\n    ref={ref}\n    className={cn(\"text-sm [&_p]:leading-relaxed\", className)}\n    {...props}\n  />\n))\nAlertDescription.displayName = \"AlertDescription\"\n\nexport { Alert, AlertTitle, AlertDescription }\n",
      "type": "registry:ui",
      "target": "components/ui/alert.tsx"
    }
  ]
}
```

I don't know what is the business rule here, so it is hard for me to come up with I fix.

For example:
- Is the `target` from the registry always present?
- When should we overwrite the `targetDir` and `filePath`?

I could create a PR to fix this, but I need some input on the questions above.
Maybe @shadcn could help clarifying some of the questions? 🙏

**Comment by stekatag** [comment] 2024-10-20 17:19
Same issue as well. The new CLI completely ignores the aliases.

**Comment by Borcioo** [comment] 2024-10-20 22:51
+1

**Comment by jpkontreras** [comment] 2024-10-20 23:17
im just a dev in a sunday wanting this to work 😭

**Comment by matheuspegorari** [comment] 2024-10-21 01:21
I'm new to shadcn and just started using today, and I'm having this issue with Next a new app.

This does not makes sense with current docs.
![image](https://github.com/user-attachments/assets/ddb1473b-ae99-4e1a-897c-ad3513c25749)

**Comment by agengdp** [comment] 2024-10-21 16:55
+1

**Comment by ilhamgepe** [comment] 2024-10-21 18:04
I hope this is fixed soon 😭

**Comment by matheuspergoli** [comment] 2024-10-21 20:04
+1

**Comment by eriknyk** [comment] 2024-10-21 23:43
any fix?

**Comment by thimvanamersfoort** [comment] 2024-10-22 20:50
+1 here, trying to install in a fresh Laravel Breeze application and the aliases are installed in my root directory, instead of `resources/ts`, see my configs here:

```json
{
  "compilerOptions": {
    "allowJs": true,
    "module": "ESNext",
    "moduleResolution": "bundler",
    "jsx": "react-jsx",
    "strict": true,
    "isolatedModules": true,
    "skipLibCheck": true,
    "target": "ESNext",
    "esModuleInterop": true,
    "forceConsistentCasingInFileNames": true,
    "noEmit": true,
    "baseUrl": ".",
    "paths": {
      "@/*": ["./resources/ts/*"],
      "ziggy-js": ["./vendor/tightenco/ziggy"],
      "public": ["./public"],
    },
    "types": [
      "vite/client",
    ]
  },
  "include": [
    "resources/ts/**/*.ts", 
    "resources/ts/**/*.tsx", 
    "resources/ts/**/*.d.ts",
    "resources/ts/**/*.mjs",
  ]
}
```

```json
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "default",
  "rsc": false,
  "tsx": true,
  "tailwind": {
    "config": "tailwind.config.js",
    "css": "resources/css/app.css",
    "baseColor": "neutral",
    "cssVariables": false,
    "prefix": ""
  },
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}
```

**Comment by shealan** [comment] 2024-10-23 07:39
Span up a new Laravel Breeze project today and ran into the same problem.

**Comment by sukronsabari** [comment] 2024-10-23 09:49
same issues in laravel inertia react

**Comment by caioalmeida12** [comment] 2024-10-23 11:32
+1 here

**Comment by shadcn** [comment] 2024-10-23 12:47
Looking into it. Is this Laravel only or next as well?

**Comment by ivan-plotnikov** [comment] 2024-10-23 12:49
> Looking into it. Is this Laravel only or next as well?

Laravel and Remix at least

**Comment by matheuspegorari** [comment] 2024-10-23 12:50
> Looking into it. Is this Laravel only or next as well? 

@shadcn happens on next too as seen in this comment: https://github.com/shadcn-ui/ui/issues/5433#issuecomment-2425366901

**Comment by shadcn** [comment] 2024-10-23 13:36
I pushed a fix for it. Can we confirm if it's working now?

**Comment by abcfstal** [comment] 2024-10-23 13:38
> I pushed a fix for it. Can we confirm if it's working now?

Appears to be working again in my limited testing, thanks!

**Comment by natemking** [comment] 2024-10-23 13:39
Confirmed working in Next

**Comment by dannyhobby93** [comment] 2024-10-23 13:41
Worked for me in my Laravel app.

**Comment by ivan-plotnikov** [comment] 2024-10-23 13:42
Working in Laravel. Thank you!

**Comment by stekatag** [comment] 2024-10-23 13:46
I can also confirm that the issue is gone in Laravel. Thank you!

**Closed** 2024-10-23 13:50 UTC
Labels: bug, area: shadcn

**Comment by shmuli9** [comment] 2024-10-23 14:51
I am still having issues (not with Laravel, but I think related to this issue), see [here](https://github.com/shadcn-ui/ui/issues/5436#issuecomment-2432488352)

**Comment by Fitipaldi007** [comment] 2024-10-23 21:30
Working for me in Remix

**Comment by shealan** [comment] 2024-10-23 22:06
Confirmed fixed in Laravel. Thank you!

**Comment by ilhamgepe** [comment] 2024-10-24 05:24
thank you. working on laravel inertia with shadcn@latest ( 2.1.1)
