### ISSUE TITLE
[bug]: Error in documentation of combobox

### ISSUE THREAD

**Issue by Invito101** [shadcn-ui/ui#3757] opened 2024-05-16 14:06 UTC
### Describe the bug

There's an error in the documentation of Combobox ( https://ui.shadcn.com/docs/components/combobox ). The components after the CommandInput needs to wrapped around CommandList according to the Command docs ( https://ui.shadcn.com/docs/components/command ).

![shadcnerror](https://github.com/shadcn-ui/ui/assets/60433065/119c36b8-597b-4ebf-aa30-a13aeb7ae4ac)

### Affected component/components

Combobox

### How to reproduce

1. Go to the code for the examples given in the Combobox docs ( https://ui.shadcn.com/docs/components/combobox )
2. Running that code as a component gives an error.

### Codesandbox/StackBlitz link

https://ui.shadcn.com/docs/components/combobox#combobox

### System Info

```bash
none
```

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues

**Comment by TanishqSharma2022** [comment] 2024-05-17 12:02
I will be fixing this. Not a bug, its just a typo ig.

**Comment by Invito101** [comment] 2024-05-17 12:41
> I will be fixing this. Not a bug, its just a typo ig.

I initially marked it as a bug instead of a typo because it's not just a simple spelling mistake, it causes an error that is quite complex to debug, especially for newbies like me. However, if it's not a significant issue, I will use the 'typo' label instead in the future.

**Comment by lucasfarias2** [comment] 2024-05-20 09:58
Quick fix for this: Just wrap your `<CommandEmpty> and <CommandGroup>` with `<CommandList>`

**Comment by Invito101** [comment] 2024-05-20 10:16
> Quick fix for this: Just wrap your `<CommandEmpty>` and `<CommandGroup>` with `<CommandList>`

Yes, I just reported so that the documentation can be fixed.

**Comment by lanyun1103** [comment] 2024-05-28 03:02
Same problem, it almost cost me a morning to check if there are any problems with my understanding of react

**Comment by gajakannan** [comment] 2024-05-30 00:23
I was banging my head for 3 days on this particular issue, tried several different things, and for a newbie, as @Invito101 said not easy to find out what is causing this issue until I decided to look at the issue log. was such a simple fix. I agree this needs to be updated in the document, otherwise people like me almost would have given up on combobox and used something else just because we couldnt get to this...

**Closed** 2024-10-21 02:30 UTC
Labels: bug
