### ISSUE TITLE
error 404 

### ISSUE THREAD

**Issue by burhan-maliksher** [shadcn-ui/ui#1439] opened 2023-09-04 06:18 UTC
on integrating shadcn in next js 13.once the app reloads it says 404.

**Comment by muradbu** [comment] 2023-09-04 13:15
Same issue

**Comment by ShaikRehan123** [comment] 2023-09-05 09:26
Can you share your directory, maybe duplicate of https://github.com/shadcn-ui/ui/issues/755

**Comment by burhan-maliksher** [comment] 2023-09-05 15:52
> Can you share your directory, maybe duplicate of #755

thanks for sharing reference issue resolved . as it was creating a new app directory outside src directory

**Comment by burhan-maliksher** [comment] 2023-09-05 15:53
> Same issue
check these links this worked for me :
1.https://github.com/shadcn-ui/ui/issues/755#issuecomment-1633710780
2.https://github.com/shadcn-ui/ui/issues/755#issuecomment-1615939390

**Closed** 2023-09-05 15:54 UTC
