### ISSUE TITLE
Toast not showing inside useEffect

### ISSUE THREAD

**Issue by TenzingT-Lama2001** [shadcn-ui/ui#1674] opened 2023-10-04 17:08 UTC
This is a snippet of my client component. The toast notification is not shown inside the useEffect. why is that so? are we not allowed to use it? I do get the logs "I am here" and logs inside setSession as well. setSession is just a regular function its not setting any state.
```
"use client"
export default function DashboardLayout({ children }: DashboardLayoutProps) {
  
  const { toast } = useToast()
  React.useEffect(() => {

    const queryParams = new URLSearchParams(window.location.search);
    const authSuccess = queryParams.get("authSuccess");
    const accessToken = getAccessTokenFromCookie() as string;
    if (authSuccess === "true") {
      console.log("I am here");
      setSession(accessToken)
      toast({
        title: "Login successful",
        description: "You are now logged in.",
      })

    } else if (authSuccess === "false") {

      console.log("Google authentication failed.");
    }
  }, [toast]);
  }
```

**Comment by shakibhasan09** [comment] 2023-10-04 22:45
You can try [] instead [toast]

**Comment by miquelvir** [comment] 2023-10-21 22:49
I have not been able to reproduce. Toast inside of useEffect works.

```tsx
"use client"

import { Button } from "@/registry/default/ui/button"
import { ToastAction } from "@/registry/default/ui/toast"
import { useToast } from "@/registry/default/ui/use-toast"
import { useEffect } from "react"

export default function ToastDemo() {
  const { toast } = useToast()
  useEffect(() => {
    toast({
      title: "Scheduled: Catch up ",
      description: "Friday, February 10, 2023 at 5:57 PM",
      action: (
        <ToastAction altText="Goto schedule to undo">Undo</ToastAction>
      ),
    })
  }, [toast])

  return (
    <Button
      variant="outline"
      onClick={() => {
        
      }}
    >
      Add to calendar
    </Button>
  )
}
```

![image](https://github.com/shadcn-ui/ui/assets/41950283/e5b3cfc6-8f6e-428b-b3ec-2966f3088639)

Provide a codepen where the issue can be reproduced or consider closing.

**Comment by miquelvir** [comment] 2023-10-21 22:52
Consider if you have the same question as #1633. The following also works:

```tsx
"use client"

import { Button } from "@/registry/default/ui/button"
import { ToastAction } from "@/registry/default/ui/toast"
import { useToast } from "@/registry/default/ui/use-toast"
import { useEffect } from "react"
import { useSearchParams } from 'next/navigation'

export default function ToastDemo() {
  const { toast } = useToast()
  const searchParams = useSearchParams()
  useEffect(() => {
    if (searchParams?.get("a") === "b"){
      toast({
        title: "Scheduled: Catch up ",
        description: "Friday, February 10, 2023 at 5:57 PM",
        action: (
          <ToastAction altText="Goto schedule to undo">Undo</ToastAction>
        ),
      })
    }
  }, [toast, searchParams])

  return (
    <Button
      variant="outline"
      onClick={() => {
        
      }}
    >
      Add to calendar
    </Button>
  )
}
```

**Comment by russelh15** [comment] 2023-11-01 19:58
I'm running into the same issue on next 13.5.6

Adding a setTimeout works.

This is happening on a client component within a server rendered page.

page ("use server") -> component ("use client")


```
useEffect(() => {
      toast({
        title: "Hold tight!",
        description:
          "We're working on importing your data. This may take a few minutes.",
      })
  }, [toast])
```

**Closed** 2023-11-02 13:35 UTC

**Comment by adherb** [comment] 2024-01-23 22:15
It's because the toast system hasn't initialised before the first render. Add a condition check and it will work as expected:

```
useEffect(() => {
  if (state.message) {
   toast({
        title: "Hold tight!",
        description:
          "We're working on importing your data. This may take a few minutes.",
      })
  }
}, [state, toast]);
```

**Comment by MateoPresaCastro** [comment] 2024-06-12 17:01
I fixed it by setting in state if the component has mounted or not.

```tsx
"use client";

import { useToast } from "@/components/ui/use-toast";
import { useEffect, useState } from "react";

export function ToastWithTitle() {
  const { toast } = useToast();
  const [mounted, setMounted] = useState(false);

  useEffect(() => {
    setMounted(true);
  }, []);

  useEffect(() => {
    if (!mounted) return;
    toast({
      title: "Title example",
      description: "Description example",
    });
  }, [toast, mounted]);

  return null;
}

```
