### ISSUE TITLE
Request for Addition of Side Navigation Menu with Icons

### ISSUE THREAD

**Issue by portal7** [shadcn-ui/ui#1287] opened 2023-08-19 14:34 UTC
Hello Shadcn Team,
I would like to request the addition of a Side Navigation Menu with Icons to enhance the user experience and navigation in the project. This feature would significantly improve the accessibility and usability of the platform.

**Details:**
- **Feature**: Side Navigation Menu
- **Benefit**: Improved navigation and accessibility
- **Icon**: Icons for each menu item
- **Purpose**: Enhance user experience

Implementing this feature would make the Shadcn project more user-friendly and visually appealing. Looking forward to your consideration.

Thank you

**Comment by portal7** [comment] 2023-08-27 13:24
Anyone? No one is interested?

**Comment by lacymorrow** [comment] 2023-12-07 15:20
I believe this is a duplicate of #667 .

For what it's worth, I build my own mostly but the best suggestions were:
- The example music app (used in one of my own apps): https://ui.shadcn.com/examples/music
- This guys' example app (collapsible, basically what I built, but simpler): https://github.com/gaofubin/t3-app-template/tree/main
- This tailwind solution: https://play.tailwindcss.com/7Qt66m0U5q?layout=preview
- Taxonomy solution: https://github.com/shadcn-ui/taxonomy/blob/main/components/sidebar-nav.tsx

**Comment by gaofubin** [comment] 2023-12-08 01:51
This is the admin template I designed, which contains sidebar and mobile sidebar. I hope it can help you.
Git repo: https://github.com/gaofubin/t3-app-template/tree/main
Demo address: [t3-app-template.vercel.app](https://t3-app-template.vercel.app/)
light:
<img width="1440" alt="light" src="https://github.com/shadcn-ui/ui/assets/20453017/a658a895-0fdd-4268-9a3c-2e103c84e5c6">

dark:
<img width="1440" alt="dark" src="https://github.com/shadcn-ui/ui/assets/20453017/c0b1ec24-417f-4ea2-8186-728fe5c386bc">

**Comment by gaofubin** [comment] 2023-12-08 04:12
@lacymorrow Hi, thank you for using it. I would like to ask if you can help me change the hover of the secondary menu to display a submenu. If so, you can help me raise a PR. Thank you.

**Comment by lacymorrow** [comment] 2023-12-08 04:32
I may not be of much help as I’m spread a little thin at the moment, but could you describe what you want in a little more detail?

**Comment by JRebertt** [comment] 2023-12-22 09:22
@lacymorrow I think you guys should totally release this model to us, it's just awesome

**Comment by lacymorrow** [comment] 2023-12-23 01:04
[Archive.zip](https://github.com/shadcn-ui/ui/files/13757472/Archive.zip)
Here is my tweaked version of @gaofubin 's component.

```ts
export const nav: NavItem[] = [
  {
    title: "Home",
    icon: LightningBoltIcon,
    href: '/',
    color: "text-sky-500",
  },
  {
    title: "Programs",
    icon: Building2Icon,
    href: '/programs',
    color: "text-sky-500",
  },
  {
    title: "Sites",
    icon: BuildingIcon,
    href: 'sites',
    color: "text-green-500",
    items: [
      {
        title: "Systems",
        icon: ActivityIcon,
        color: "text-pink-500",
        href: '/sites/systems',
      },
    ],
  },
];
```

**Comment by ceedadev** [comment] 2023-12-23 08:10
hi all, shad just released new components. It has new [ Mail example](https://ui.shadcn.com/examples/mail) and it has a killer sidenavbar.

**Comment by lacymorrow** [comment] 2023-12-28 17:37
That's sick!

This can be closed most likely.

**Comment by ArielMejiaDev** [comment] 2023-12-28 19:58
The Mail example has a great side navbar example, here is the code to find it:

- [Used here](https://github.com/shadcn-ui/ui/blob/main/apps/www/app/examples/mail/components/mail.tsx#L87)
- [The Nav component here](https://github.com/shadcn-ui/ui/blob/main/apps/www/app/examples/mail/components/nav.tsx#L24)

**Closed** 2023-12-29 17:55 UTC

**Comment by elijaholmos** [comment] 2024-03-08 22:10
How could I make this sidebar nav stay fixed on the left side of the screen while I scroll through my main page content? I tried adding the fixed, sticky, etc position properties and it didn't really work.

**Comment by lacymorrow** [comment] 2024-03-12 02:57
Think about the way your content is structured. The reason the handle disappeared is likely because it was stretched down the page to 50% the height of your content. If using the resizable panels, they must stay at 100vh (max). You need a child element to scroll, rather than the resizable panel.

I've been able to accomplish this using the scrollarea component, but there are bugs that make it very difficult. I recommend using a regular div with a height+overflow auto
