### ISSUE TITLE
Does it work on expo?

### ISSUE THREAD

**Issue by Samuele-Barbiera** [shadcn-ui/ui#73] opened 2023-02-10 09:39 UTC
having the possibility to work with expo or react native

**Comment by shadcn** [comment] 2023-02-12 05:54
I have not tried it yet. Would be helpful if someone could test this and report back.

**Comment by corysimmons** [comment] 2023-02-13 07:18
I'm sure it doesn't. There are mentions of `<div>` etc. throughout the codebase. If it were React Native (Expo) compatible, those would have to be `<View>`s.

Something like this is **sorely** missing in the ReactNative/Expo/[Solito](https://solito.dev/) ecosystem.

[Tamagui](https://tamagui.dev/) is trying to fill the hole, but the API is styled-system instead of Tailwind 😞 and the design isn't on point like Radix or Tailwind.

**Comment by AyoCodess** [comment] 2023-04-24 04:50
Im bumping into this issue. I want to use this library cross platform but as highlighted already it does not support reactive native components. 

What im doing now is assessing if it’s worth the time and energy to convert these web components into react native components considering that it uses radix ui primitives.

**Comment by corysimmons** [comment] 2023-05-21 18:39
@tonyabracadabra Tamagui isn't headless. Nothing on RNW is.

**Comment by triptu** [comment] 2023-08-12 16:57
@corysimmons the components in tamagui take `unstyled` prop which make them headless, the composition API is similar to radix.

**Comment by corysimmons** [comment] 2023-08-14 02:39
@triptu If that's true, that's pretty huge. Thank you for letting me know!

**Comment by warum7** [comment] 2023-08-14 09:37
I found library here: https://ui.gluestack.io They claim to have support for all platforms. Haven't tried it out yet though. I'll try to use the unstyled components and see if I can get the shadcn styles working.

**Comment by warum7** [comment] 2023-08-18 17:29
> I found this library here: https://ui.gluestack.io They claim to have support for all platforms. Haven't tried it out yet though. I'll try to use the unstyled components and see if I can get the shadcn styles working.

So I tried it out with Tamagui. But it would only work with client components which is a dealbreaker for me when using the components with nextjs app dir. Tamagui is already looking for a solution to this but until this happens I am going to stick with the current Shadcn Radix implementation. If you're trying to integrate shadcn on native the "easiest" library to do so is probably Tamagui + Nativewind. As triptu pointed out Tamagui takes an unstyled prop and the composition API is similar to radix. With nativewind you could mimic most of the shadcn styles. Ah and if it's okay for you to use client components @expo/html-elements is a great library that allows to use semantic HTML on the web while using an equivalent on native. With that you could replace <div> elements in shadcn for instance.

**Comment by triptu** [comment] 2023-08-18 17:44
@warum7 did you try Gluestack as well? I have yet to try it. How's it compared to tamagui?

**Comment by warum7** [comment] 2023-08-18 18:37
> @warum7 did you try Gluestack as well? I have yet to try it. How's it compared to tamagui?

Yes indeed. The installation is much easier than Tamagui but it doesn't work as expected. While you can add styles you have to add them through nativewind on web because it does not come with a className prop by default. I also couldn't figure out how I can disable the styles that come out of the box. And again same issue: everything has to load on client. I think in that sense Tamagui is the better option if you're looking to mimic Shadcn. 

That being said I think that it's possible to have a shadcn-ish experience utilizing Tamagui. One could use the shadcn components for the web and copy paste them in a separate package for native while editing the types and the imports.

**Comment by MrgSub** [comment] 2023-09-05 15:53
The most time consuming task here - in my opinion - is how `shadcn` does not separate container classes and text classes.
in HTML it's valid to write ```<div>test</div>``` but not in react native as this should translate to ```<View><Text>test</Text></View>``` which means you can't share the same class name between both elements created.

**Comment by rafaell-lycan** [comment] 2023-09-10 14:52
One possible idea would be creating components using RN implementation and using a flag or prefix when adding to our project.

To avoid breaking existing projects, the initial configuration could be set to `components.json`:

```
{
  ...
  "react-native": true
}
```

This property could be added during the setup/init phase or even included using a flag `--react-native`.

With this in mind, the command `add` would only include components made for React Native using proper components, such as:
- Button: Using [`Pressable `](https://reactnative.dev/docs/pressable)
- Card: Using something like [`View`](https://reactnative.dev/docs/view) or even [`TouchableOpacity`](https://reactnative.dev/docs/touchableopacity).
- And many others.

The good part is that design-wise it could match a similar design and API contract using something like [tailwind-rn](https://github.com/vadimdemedes/tailwind-rn), [nativewind](https://github.com/marklawlor/nativewind) or something even simpler.

TBH it would be easier for someone else to start a project like this and see if the community reacts to it, as [1] the overall complexity of this project would increase [2] for something we don't know if people would use and [3] the maintenance could become a problem if that's the case. cc @shadcn 

Meanwhile, I'm using [`react-native-paper`](https://github.com/callstack/react-native-paper) which fits my needs.

**Notes:**
- Radix was designed to be used for web-only, but these RN components could have used [accessibility properties](https://reactnative.dev/docs/accessibility) in some cases;
- Also [react-native-reanimated](https://github.com/software-mansion/react-native-reanimated) would be perfect for smooth animations/transitions;

**Comment by corysimmons** [comment] 2023-09-12 23:16
It's absolutely possible to do this, but it's a huge undertaking. You'd have to make Radix RN-friendly (I looked into this in the Radix Discussions if anyone is interested), which is possible but finicky (as all RN things are). Then, you'd have to use NativeWind to copy/paste all these shadcn-ui styles to the new UI kit.

**Comment by rafaell-lycan** [comment] 2023-09-27 13:35
At least someone is trying 👻 
https://github.com/Mobilecn-UI/nativecn-ui

**Comment by corysimmons** [comment] 2023-09-27 16:14
@rafaell-lycan That lib isn't porting all the goodness of Radix primitives (a11y-friendly keyboard nav, headless, etc.). It's just porting the Tailwind classes from shadcn-ui to RN components. It's equivalent to using _any_ styled lib for RN.

Compare the complexity of these two files:
- Unstyled Radix with all its a11y stuff: https://github.com/radix-ui/primitives/blob/main/packages/react/tabs/src/Tabs.tsx
- Hard-styled RN component: https://github.com/Mobilecn-UI/nativecn-ui/blob/main/components/Tabs.tsx

[One of these things is not like the other.](https://www.youtube.com/watch?v=ueZ6tvqhk8U)

Again, the only way to properly do this would be to convert Radix UI's [mentions of divs](https://github.com/radix-ui/primitives/blob/c31c97274ff357aea99afe6c01c1c8c58b6356e0/packages/react/tabs/src/Tabs.tsx#L217) and other DOM elements to RN primitives. Once you do that (and create a standalone `rn-radix-ui` repo), _then_ you can go over it with NativeWind and copy/paste shadcn-ui components over to its own repo (e.g. `rn-shadcn-ui`).

If you're feeling particularly ambitious, you could do something like Fernando Rojo is doing with his project [Zeego](https://github.com/nandorojo/zeego) and make as many headless UI components into their native counterparts as possible. For instance, for a `Popover` component, you might have:

- `Popover.tsx` which serves one of the following depending on the user's client:
  - `Popover.web.tsx` that uses unstyled DOM elements to create a popover effect.
  - `Popover.ios.tsx` that hooks into SwiftUI to use the actual native SwiftUI Popover equivalent.
  - `Popover.android.tsx` that hooks into Jetpack Compose to use the Android Popover equivalent.

So you'd have to have a decent amount of SwiftUI and Jetpack Compose knowledge. Although I suspect ChatGPT could help out a _lot_ with this so you wouldn't have to be an iOS or Android dev or anything. 😂 

If anyone wants to fork Radix UI and start work on this project, I'd be more than happy to consult in Discord and get you going on all aspects. I don't have the time right now to undertake the whole project (or keep it in sync with Radix UI, or in sync with SwiftUI and Jetpack Compose) since it will be a lot of busy work for a very long time.

But if someone did tackle this problem, it would make creating cross-platform apps insanely nice and probably become a 10k+ Star library.

**Comment by WilliamWelsh** [comment] 2023-09-30 18:13
I was able to remake the button component with the same syntax as regular web, meaning you *DON'T* have to wrap text in a Text component, or in a label prop like `nativecn-ui`. This is with Tamagu unstyled and Nativewind.

<img width="1800" alt="image" src="https://github.com/shadcn-ui/ui/assets/16886888/177b8fd9-299c-4218-be1a-1011122c4743">

**Comment by SushritPasupuleti** [comment] 2023-10-05 05:07
> I was able to remake the button component with the same syntax as regular web, meaning you _DON'T_ have to wrap text in a Text component, or in a label prop like `nativecn-ui`. This is with Tamagu unstyled and Nativewind.
> 
> <img alt="image" width="1800" src="https://user-images.githubusercontent.com/16886888/271788790-177b8fd9-299c-4218-be1a-1011122c4743.png">

This is looking good, I am going to try something like modals to see how far this can go.

**Comment by olehmelnyk** [comment] 2023-10-15 22:31
hey, have you heard about mitosis? https://github.com/BuilderIO/mitosis 
It looks like it can convert JSX-like components to other frameworks, including React Native, Angular, Vue, etc. - so MAYBE with it - it would be possible to make shadcn/ui framework agnostic

**Comment by TheUltDev** [comment] 2023-10-16 00:47
I'm working on this currently.

I'm using shadcn-ui as a styleguide. Radix UI for web. Wix's RN UI Lib for native.
Prototyping in Figma and exporting to RN/Expo via my plugin: https://figma-to-react-native.com

<img width="1261" alt="Screenshot 2023-10-15 at 7 44 57 PM" src="https://github.com/shadcn-ui/ui/assets/2079305/bbf34b9d-386d-4f88-a196-8e07032ab791">

**Comment by oguzhane** [comment] 2023-10-16 05:28
@TheUltDev this sounds so good to be true!  looking forward to it to try😊

**Comment by shadcn** [comment] 2023-10-21 14:25
@TheUltDev Thanks for your work on this. I'm going to close this for now as unplanned and link to your repo when launched.

**Closed by shadcn** 2023-10-21 14:25 UTC

**Comment by ro-mgh** [comment] 2024-01-07 15:24
For those who like me are looking for a StyleSheet solution, I'm working on a [malla UI](https://github.com/ro-mgh/mallaui) library. I am also developing a Figma file for easy design compilation. 

![Simulator Screenshot - iPhone 14 - 2024-01-07 at 18 10 13 Medium](https://github.com/shadcn-ui/ui/assets/58989752/75e8b9b8-75ae-4030-85d2-ce0b95522264) ![Simulator Screenshot - iPhone 14 - 2024-01-07 at 18 10 15 Medium](https://github.com/shadcn-ui/ui/assets/58989752/54c1c445-f58c-41a3-8fc4-c9d0738d80e3)

<img width="462" alt="Screenshot 2024-01-07 at 18 22 42" src="https://github.com/shadcn-ui/ui/assets/58989752/7cd693cc-b275-49b4-a673-01a7cb38999d">

P.S. @shadcn, your idea is brilliant, thank you!

**Comment by trevorpfiz** [comment] 2024-02-07 15:30
[react-native-reusables](https://github.com/mrzachnugent/react-native-reusables) seems like the best option right now

**Comment by AurelianSpodarec** [comment] 2024-06-14 20:47
Any updates? :/

@theultdev - how ya doing? :D

**Comment by TheUltDev** [comment] 2024-06-16 20:52
@AurelianSpodarec

I've been focused on the Figma -> RN plugin. I finished the final update needed to continue with EXO (the primitives + UI library) You can try it here: https://figma-to-react-native.com

As far as the UI kit goes, it's about 2-3 weeks away from being ready for the public, you can see and use a preview of the lib here: https://exo.ult.dev/

Note that most of the components will be designed and generated by the plugin, I'm currently working on building them all in Figma.

For now I would suggest going with [react-native-reusables](https://github.com/mrzachnugent/react-native-reusables) if you would like to use NativeWind and don't want to sync Figma mockups with your app.

If you would like to use Unistyles and create your design components in Figma, stay tuned over the next month, you can follow me on X for updates: https://x.com/theultdev

**Comment by codeogc** [comment] 2024-08-26 11:53
@EvanBacon has this changed with Dom components?
