### ISSUE TITLE
Support for exit animations on Dialogs, Menus,...

### ISSUE THREAD

**Issue by sanvishal** [shadcn-ui/ui#72] opened 2023-02-10 08:08 UTC
I've been using this component library for a couple of days now, LOVING IT!

The only part that's missing is the exit animations, especially for the dialogs and menu components. They `animate-in` nicely but they disappear instantly on unmount. I'm somewhat new to radixUI, but I read [this](https://www.radix-ui.com/docs/primitives/overview/animation) from radix which basically uses the `data-[state=open/close]` attributes to animate the state transitions (and this is what [accordions](https://github.com/shadcn/ui/blob/main/apps/www/components/ui/accordion.tsx#L53) seem to use on this library with animations declared on tw config)

So, is not having exit animations on certain components an intentional design choice?

**Comment by shadcn** [comment] 2023-02-10 08:32
@sanvishal Some of the exit animations are intentionally not added. 

Example: for alert dialog you want visual feedback (animation) when the dialog enters but you want it to "get it out of your way" when exit. (I tried adding exit animations and it felt weird/sluggish).

Some are probably oversight on my part. Can you let me know which components and I can fix?

Thank you.

**Comment by sanvishal** [comment] 2023-02-10 08:47
thanks, but for now, I've only seen them missing on dialogs, dropdown menus, tooltips, and popovers. I think your justification makes sense to me in some cases. 

I'll create a PR or a separate issue if I find any other components.

**Comment by natac13** [comment] 2023-02-12 17:41
I was wondering this myself today. I was trying to modify the dialog to be a slide in nav from the left. I was able to get the enter slide in going but the exit I'm having trouble with. 
I have tried force mount on the portal but I was getting sluggish animations

**Comment by joaom00** [comment] 2023-02-12 17:58
Hey @natac13, how are you doing the exit animation?

**Comment by natac13** [comment] 2023-02-13 00:12
> Hey @natac13, how are you doing the exit animation?

I followed something similar to [this](https://github.com/radix-ui/primitives/discussions/1058). However I was not very successful. 
My idea was to remove the framer motion stuff from the example but leave the `open` prop. I then made a duplicate of the `DialogContent` component from this library and used the `forceMount` prop on the portal then tried to use the `data-[state=closed]` prefix to handle the exit animation but was getting bad results

**Comment by joaom00** [comment] 2023-02-13 03:04
With tailwind, just use `data-*` modifier: `data-[state=open]:animate-show data-[state=closed]:animate-hide`

https://codesandbox.io/p/sandbox/pedantic-aryabhata-1ykgmk?file=%2FApp.jsx

**Comment by sanvishal** [comment] 2023-02-14 14:10
I tried to add an exit animation to the, but it just doesn't work for some reason. I added the dialog component in the `next-template`  imported from `@/components/ui/dialog`.

I added `data-[state=closed]:animate-out data-[state=closed]:fade-out-10 data-[state=closed]:zoom-out-50` to the `<DialogContent />` [here](https://github.com/shadcn/ui/blob/main/apps/www/components/ui/dialog.tsx#L51)

I've also added logs to the `onAnimationStart/End` callback, this is what I got after opening and closing the dialog 1 time

```
start anim: enter
end anim: enter
```

additionally, I should've also gotten the `exit` animation log too while closing the dialog, but it seems like radix did not suspend the "unmounting" till the animation finishes up. Is this a radix-specific problem or some other? because the codesandbox by @joaom00 seems to work just fine.

**Comment by its-monotype** [comment] 2023-02-14 14:12
> I tried to add an exit animation to the dialog component, but it just doesn't work for some reason. I added the dialog component in the `next-template`  imported from `@/components/ui/dialog`.
> 
> I added `data-[state=closed]:animate-out data-[state=closed]:fade-out-10 data-[state=closed]:zoom-out-50` to the `<DialogContent />` [here](https://github.com/shadcn/ui/blob/main/apps/www/components/ui/dialog.tsx#L51)
> 
> I've also added logs to the `onAnimationStart/End` callback, this is what I got after opening and closing the dialog 1 time
> 
> ```
> start anim: enter
> end anim: enter
> ```
> 
> additionally, I should've also gotten the `exit` animation log too while closing the dialog, but it seems like radix did not suspend the "unmounting" till the animation finishes up. Is this a radix-specific problem or some other? because the codesandbox by @joaom00 seems to work just fine.

I have the same problem when I tried to add exit animations to Radix components using tailwind-animate plugin, however with self writing animations everything works fine

**Comment by sanvishal** [comment] 2023-02-14 14:26
well, that's a minor inconvenience, TIL :)

thanks, I'll try with non-tailwindy animations!

**Comment by its-monotype** [comment] 2023-02-14 14:54
@joaom00 Wow, it’s strange, but I really tried it now and it works, I don’t even know what happened then, maybe a bug or blunted somewhere. Thankee!

**Comment by its-monotype** [comment] 2023-02-14 16:05
@joaom00 Is it possible to do something with the fact that because of '-translate-x-1/2 -translate-y-1/2' the animation starts from the corner?

**Comment by joaom00** [comment] 2023-02-14 16:54
@its-monotype Yes, I updated the example with tailwind-animate to match the one in tailwind.config

**Comment by sanvishal** [comment] 2023-02-15 05:52
> @joaom00 Is it possible to do something with the fact that because of '-translate-x-1/2 -translate-y-1/2' the animation starts from the corner?

yep, that seems to be the issue, thanks @joaom00

**Comment by digoburigo** [comment] 2023-02-27 13:15
Integration with this makes sense? [tailwind-radix](https://github.com/ecklf/tailwindcss-radix)

**Comment by baumerdev** [comment] 2023-03-15 14:50
I played a little bit with the code of shadcn/ui's Dialog. The main problem seemed to be the `<div>` between `DialogPrimitive.Portal` and `{children}`:

```typescript
const DialogPortal = ({
  className,
  children,
  ...props
}: DialogPrimitive.DialogPortalProps) => (
  <DialogPrimitive.Portal className={cn(className)} {...props}>
    <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center">
      {children}
    </div>
  </DialogPrimitive.Portal>
)
DialogPortal.displayName = DialogPrimitive.Portal.displayName
```

This causes Radix UI's Portal to ignore animations on Overlay and Content and thus removing the Portal's content immediately. Therefore none of the animation you might have added were visible because the elements weren't longer part of the DOM.

In shadcn/ui#127 I removed the `<div>`. Problem now is that the positioning of the Overlay and Content relied on the parent div which used CSS's flex. Now the components are directly in the DOM and we need to position them on their own with fixed. And because this positioning is a little bit more complex the animations needed to be as well.

The result should be visually the same with an additional exit animation.

**Comment by AlvaroAquijeDiaz** [comment] 2023-06-06 15:31
Any updates on this issue 🤕?

**Comment by baumerdev** [comment] 2023-06-07 17:42
@AlvaroAquijeDiaz  My PR hasn't been merged to the code base yet and meanwhile the upstream code has changed. If I find time in the next days I can adjust my PR for the current master. But if it it's urgent, the code changes in my PR/previous comment should still work if you change this in your code accordingly.

**Comment by baumerdev** [comment] 2023-06-12 15:45
Based on the current main branch I re-did the exit animation for dialog and alert-dialog as well as some other components. If anyone needs it _now_, see the diff in my PR what to change.

**Comment by yav-balance** [comment] 2023-06-19 12:17
> This causes Radix UI's Portal to ignore animations on Overlay and Content and thus removing the Portal's content immediately. Therefore none of the animation you might have added were visible because the elements weren't longer part of the DOM.

@baumerdev I've ran into this issue before and had solved it by adding a "fake" animation to the div in question which doesn't do anything visually different: 

```js
fakeAnimation: {
  from: { opacity: '1' },
  to: { opacity: '1' },
},
```

That way `Radix.Portal` doesn't ignore the underlying `Radix.Content` animation.

**Comment by eIIisd** [comment] 2023-07-21 17:34
> > This causes Radix UI's Portal to ignore animations on Overlay and Content and thus removing the Portal's content immediately. Therefore none of the animation you might have added were visible because the elements weren't longer part of the DOM.
> 
> @baumerdev I've ran into this issue before and had solved it by adding a "fake" animation to the div in question which doesn't do anything visually different:
> 
> ```js
> fakeAnimation: {
>   from: { opacity: '1' },
>   to: { opacity: '1' },
> },
> ```
> 
> That way `Radix.Portal` doesn't ignore the underlying `Radix.Content` animation.

Hey, can you provide full details on how you achieved this? Unsure if this snippet is for some animation library?

**Comment by yavorpunchev** [comment] 2023-07-23 12:24
> Hey, can you provide full details on how you achieved this? Unsure if this snippet is for some animation library?
This is a pure CSS animation, the library doesn't really matter (the above snippet was done with stitches, but can work with tailwind or any styling library of your choice).

**Comment by eIIisd** [comment] 2023-07-24 11:36
> done

Would love to get this working but can't seem to replicate the fix you descibe - any chance you could drop a sandbox?

**Comment by eIIisd** [comment] 2023-07-24 11:37
> > Hey, can you provide full details on how you achieved this? Unsure if this snippet is for some animation library?
> 
> This is a pure CSS animation, the library doesn't really matter (the above snippet was done with stitches, but can work with tailwind or any styling library of your choice).

Would love to get this working but can't seem to replicate the fix you descibe - any chance you could drop a sandbox?

**Comment by yavorpunchev** [comment] 2023-07-25 07:39
@eIIisd sure, [here's a repo with the fix](https://github.com/yavorpunchev/radix-exit-transition). One thing I forgot to mention is that the div in question has to he a `Dialog.Overlay` under the hood so that we can hook into the appropriate open/closed data attributes

**Comment by shadcn** [comment] 2023-10-21 14:25
We now have exit animations on all components.

**Closed** 2023-10-21 14:25 UTC

**Comment by MateusPitura** [comment] 2024-07-04 18:34
After hours of trying to solve this and to searching a lot, I solve my problem. The post of @baumerdev helps me. I'll brief my learn:

1. To use data-state in tailwind do
```
data-[state=closed]:your-animation
```
3. Don't put a div between Portal and Overlay or Content, otherwise the exit animation will you fail
4. I'm centralizing my dialog with 
```
fixed inset-0
``` 
When I put this code in the className of Content, I can't close the portal clicking outside, so I discovered that I can nest the content inside the overlay, and pow! I put the above code into overlay and it works for me

**Comment by OmarHedeya95** [comment] 2024-12-31 12:56
@MateusPitura exactly what worked for me (did not need the fixed inset-0 in my case). Thank you!

**Comment by NickWoodward** [comment] 2025-02-03 06:23
> After hours of trying to solve this and to searching a lot, I solve my problem. The post of [@baumerdev](https://github.com/baumerdev) helps me. I'll brief my learn:
> 
>     1. To use data-state in tailwind do
> 
> 
> ```
> data-[state=closed]:your-animation
> ```
> 
>     3. Don't put a div between Portal and Overlay or Content, otherwise the exit animation will you fail
> 
>     4. I'm centralizing my dialog with
> 
> 
> ```
> fixed inset-0
> ```
> 
> When I put this code in the className of Content, I can't close the portal clicking outside, so I discovered that I can nest the content inside the overlay, and pow! I put the above code into overlay and it works for me

This is what my dialog looks like by default - no div between but still no exit animation :/

```
<DialogPortal>
    <DialogOverlay />
    <DialogPrimitive.Content
      ref={ref}
      className={cn(
        "fixed left-[50%] top-[50%] z-50 grid w-full max-w-lg translate-x-[-50%] translate-y-[-50%] gap-4 border border-slate-200 bg-white p-6 shadow-lg duration-200 data-[state=open]:animate-in data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=open]:fade-in-0 data-[state=closed]:zoom-out-95 data-[state=open]:zoom-in-95 data-[state=closed]:slide-out-to-left-1/2 data-[state=closed]:slide-out-to-top-[48%] data-[state=open]:slide-in-from-left-1/2 data-[state=open]:slide-in-from-top-[48%] sm:rounded-lg dark:border-slate-800 dark:bg-slate-950",
        className
      )}
      {...props}
    >
      {children}
      <DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm opacity-70 ring-offset-white transition-opacity hover:opacity-100 focus:outline-none focus:ring-2 focus:ring-slate-950 focus:ring-offset-2 disabled:pointer-events-none data-[state=open]:bg-slate-100 data-[state=open]:text-slate-500 dark:ring-offset-slate-950 dark:focus:ring-slate-300 dark:data-[state=open]:bg-slate-800 dark:data-[state=open]:text-slate-400">
        <CloseIcon className="h-4 w-4" />
        <span className="sr-only">Close</span>
      </DialogPrimitive.Close>
    </DialogPrimitive.Content>
  </DialogPortal>

```

**Comment by MateusPitura** [comment] 2025-02-03 23:19
@NickWoodward try to nest the `DialogPrimitive.Content` inside `DialogOverlay`, something like 

```
<DialogPortal>
   <DialogOverlay>
      <DialogPrimitive.Content ...
   <DialogOverlay>
```

**Comment by NickWoodward** [comment] 2025-02-05 09:52
> [@NickWoodward](https://github.com/NickWoodward) try to nest the `DialogPrimitive.Content` inside `DialogOverlay`, something like
> 
> ```
> <DialogPortal>
>    <DialogOverlay>
>       <DialogPrimitive.Content ...
>    <DialogOverlay>
> ```

No luck unfortunately, thanks though!
